### ISSUE TITLE
IndexOutOfRangeException in MessageSecurityOverHttpElement when creating WCF client from service reference

### ISSUE THREAD

**Issue by mol** [dotnet/docs#13818]
I have a normal WCF service reference created using 'Add Service Reference' in an application used by thousands of people.

An instance of the client is created using `new MyServiceClient()` and it works 99% of the time, but for some users it can fail with an `IndexOutOfRangeException`. I have been unable to reproduce, but from my error reports it seems it might only happen when the application is set to start with Windows, so might be some kind of race condition with some underlying Windows service on startup?

```
Exception (-2146233080): 
System.IndexOutOfRangeException: Index was outside the bounds of the array. 
at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext() 
at System.Configuration.PropertyInformationCollection..ctor(ConfigurationElement thisElement) 
at System.ServiceModel.Configuration.MessageSecurityOverHttpElement.ApplyConfiguration(MessageSecurityOverHttp security) 
at System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.ApplyConfiguration(NonDualMessageSecurityOverHttp security) 
at System.ServiceModel.Description.ConfigLoader.LookupBinding(String bindingSectionName, String configurationName, BindingCollectionElement bindingCollectionElement, Binding defaultBinding) 
at System.ServiceModel.Description.ConfigLoader.LookupBinding(String bindingSectionName, String configurationName, ContextInformation context)
at System.ServiceModel.Description.ConfigLoader.LoadChannelBehaviors(ServiceEndpoint serviceEndpoint, String configurationName) 
at System.ServiceModel.ChannelFactory.ApplyConfiguration(String configurationName, Configuration configuration) 
at System.ServiceModel.ChannelFactory.InitializeEndpoint(String configurationName, EndpointAddress address) 
at System.ServiceModel.ChannelFactory`1..ctor(String endpointConfigurationName, EndpointAddress remoteAddress) 
at System.ServiceModel.ConfigurationEndpointTrait`1.CreateSimplexFactory() 
at System.ServiceModel.ClientBase`1.CreateChannelFactoryRef(EndpointTrait`1 endpointTrait) 
at System.ServiceModel.ClientBase`1.InitializeChannelFactoryRef()
```

```
<system.serviceModel>
  <bindings>
    <wsHttpBinding>
	  <binding name="WSHttpBinding_IMyService">
	    <security mode="Transport">
		  <transport clientCredentialType="None" />
	    </security>
	  </binding>
    </wsHttpBinding>
  </bindings>
  <client>
    <endpoint address="https://xxxxxxxx.com/Services/MyService.svc" binding="wsHttpBinding" bindingConfiguration="WSHttpBinding_IMyService" contract="MyService.IMyService" name="WSHttpBinding_IMyService" />
  </client>
</system.serviceModel>
```

**Comment by mairaw** [comment]
Thanks for your feedback @mol but what you're describing seems like a product issue. Please report products bugs at https://developercommunity.visualstudio.com/spaces/61/index.html.

**Comment by mol** [comment]
I feel like if this was a Visual Studio issue it wouldn't work 99% of the time. The race condition has to be in .NET in relation to Windows, but I reported it here and then we'll see:
https://developercommunity.visualstudio.com/content/problem/692599/indexoutofrangeexception-in-messagesecurityoverhtt.html
