### ISSUE TITLE
Error: Splitter/consolidator worker encountered exception while consuming source data ---> System.ArgumentException: Parameter is not valid.

### ISSUE THREAD

**Issue by EmreMicrosoft** [dotnet/docs#16397]
2019-12-25 04:09:46.674731: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
=============== Training classification model ===============
Unhandled exception. System.InvalidOperationException: Splitter/consolidator worker encountered exception while consuming source data
 ---&gt; System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(String filename)
   at Microsoft.ML.Data.ImageLoadingTransformer.Mapper.&lt;&gt;c__DisplayClass4_0.&lt;MakeGetterImageDataViewType&gt;b__0(Bitmap& dst)
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.&lt;&gt;c__DisplayClass3_0.&lt;MakeGetter&gt;b__1(Bitmap& dst)
   at Microsoft.ML.Transforms.Image.ImagePixelExtractingTransformer.Mapper.&lt;&gt;c__DisplayClass5_0`1.&lt;GetGetterCore&gt;b__1(VBuffer`1& dst)
   at Microsoft.ML.Transforms.TensorFlowTransformer.TensorValueGetterVec`1.GetTensor()
   at Microsoft.ML.Transforms.TensorFlowTransformer.Mapper.UpdateCacheIfNeeded(Int64 position, ITensorValueGetter[] srcTensorGetters, String[] activeOutputColNames, OutputCache outputCache)
   at Microsoft.ML.Transforms.TensorFlowTransformer.Mapper.&lt;&gt;c__DisplayClass9_0`1.&lt;MakeGetter&gt;b__4(VBuffer`1& dst)
   at Microsoft.ML.Data.DataViewUtils.Splitter.InPipe.Impl`1.Fill()
   at Microsoft.ML.Data.DataViewUtils.Splitter.&lt;&gt;c__DisplayClass5_1.&lt;ConsolidateCore&gt;b__2()
   --- End of inner exception stack trace ---
   at Microsoft.ML.Data.DataViewUtils.Splitter.Batch.SetAll(OutPipe[] pipes)
   at Microsoft.ML.Data.DataViewUtils.Splitter.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
   at Microsoft.ML.Trainers.LbfgsTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data)
   at Microsoft.ML.Trainers.LbfgsTrainerBase`3.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Algorithms.MachineLearning.ImageClassification.Program.GenerateModel(MLContext mlContext) in C:\Users\basecamp\source\repos\Algorithms\Algorithms.MachineLearning.ImageClassification\Program.cs:line 83
   at Algorithms.MachineLearning.ImageClassification.Program.Main(String[] args) in C:\Users\basecamp\source\repos\Algorithms\Algorithms.MachineLearning.ImageClassification\Program.cs:line 31

--------------------------------------------

Program.cs:line 83 ---&gt; ITransformer model = pipeline.Fit(trainingData); 
Program.cs:line 31 ---&gt; ITransformer model = GenerateModel(mlContext);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Generate an ML.NET image classification model from a pre-trained TensorFlow model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @EmreMicrosoft 

Sorry to hear you're having issues. I was not able to reproduce the error after following the tutorial. I believe the error might be related to the data. Did you make sure to include the files in the assets in your output directory? 

> In Solution Explorer, right-click each of the files in the asset directory and subdirectories and select Properties. Under Advanced, change the value of Copy to Output Directory to Copy if newer.

Alternatively, you can edit your *.csproj* file to include the following snippet inside the `<Project>` node.

```xml
  <ItemGroup>
    <None Include="assets/*/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

If you're still having issues, I would suggest taking a look at the completed sample and compare it to your code.

https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/TransferLearningTF
