### ISSUE TITLE
this code doesn't work. The exceptions was not catched

### ISSUE THREAD

**Issue by yehanghanGE** [dotnet/docs#17645]
Got error:
System.OperationCanceledException
  HResult=0x8013153B
  Message=The operation was canceled.
  Source=mscorlib
  StackTrace:
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at MarketoApiConsole.Program.&lt;&gt;c__DisplayClass0_0.&lt;Main&gt;b__1(Int32 num) in C:\Projects\MarketoRestApi\MarketoApiConsole\Program.cs:line 42
   at System.Threading.Tasks.Parallel.&lt;&gt;c__DisplayClass30_0`2.&lt;ForEachWorker&gt;b__0(Int32 i)
   at System.Threading.Tasks.Parallel.&lt;&gt;c__DisplayClass17_0`1.&lt;ForWorker&gt;b__1()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad8b3ee-d780-0844-bc19-1f725df6fcc1
* Version Independent ID: c83570d1-5b88-06fa-b3ed-6ff984f7c310
* Content: [How to: Cancel a Parallel.For or ForEach Loop](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-cancel-a-parallel-for-or-foreach-loop#feedback)
* Content Source: [docs/standard/parallel-programming/how-to-cancel-a-parallel-for-or-foreach-loop.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-cancel-a-parallel-for-or-foreach-loop.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
I'm unable to reproduce that error. The code runs and catches the exception as expected. Can you provide more information about the environment you're running in? Are you running in debug mode?
