### ISSUE TITLE
Missing nuget package and folder path

### ISSUE THREAD

**Issue by kylelaverty** [dotnet/docs#17770]
While working through this tutorial I have found two issue:
- You need to add Microsoft.ML.OnnxRuntime as a nuget package, which is not mentioned.
- In the OnnxModelScorer.LoadModel method, there is a pipeline step of LoadImages(), the imageFolder property is set wrong. It should be referring to the class level property of imagesFolder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [Tutorial: Detect objects using an ONNX deep learning model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx#feedback)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @kylelaverty ,

Which version of ML.NET are you using?

**Comment by kylelaverty** [comment]
Hey @luisquintanilla,

I am currently using 1.5.0-preview2.

Without Microsoft.ML.OnnxRuntime in the nuget package list, this is what I get when running the tutorial project:
```
**System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'onnxruntime' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase()
   at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary)
   at Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)**
```

**Comment by luisquintanilla** [comment]
Thank you for getting back to me @kylelaverty . Version 1.5.0-preview-x is still a preview version and the tutorials in Docs use the latest stable version 1.4.0. We will make sure to update accordingly once the next stable version is released. In the meantime, for preview versions, I would suggest taking a look at the API documentation where these things are updated for the respective versions. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.onnx.onnxtransformer?view=ml-dotnet#estimator-characteristics

**Comment by celowsky** [comment]
I'm still having this issue with the latest stable release of Microsoft.ML (v1.5.1)
