### ISSUE TITLE
Issue binding appsettings when using windows service

### ISSUE THREAD

**Issue by KeishaW** [dotnet/docs#18065]
After following the instructions for 'Run your app as a Windows service' I get an error while calling the service.
See full stack trace below.

After some investigation, I realized the issue what due to some appsettings binding I did in the Startup.cs
```
var settingsConfig = new AppSettings();
Configuration.Bind("AppSettings", settingsConfig);
services.AddSingleton(settingsConfig);
```

The error happened when trying to actually use my AppSettings.

When I instead click the exe to run the grpc server it works fine and I am able to use my appsettings.
I'm not sure what the difference is for the windows service that is causing this error.

Just to confirm, I tried the grpc server as a windows service where I did not use the AppSettings and that windows service worked.

So the issue boils down to using bound AppSettings.

Here's there Greeter Service:
```
public class GreeterService : Greeter.GreeterBase
{
	private readonly ILogger<GreeterService> _logger;
	private AppSettings AppSettings { get; set; }
	public GreeterService(ILogger<GreeterService> logger, AppSettings appSettings)
	{
		_logger = logger;
		AppSettings = appSettings;
	}

	public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
	{
		string info = AppSettings.Info.Name;
		return Task.FromResult(new HelloReply
		{
			Message = $"Hello {request.Name} @ {info}"
		});
	}
}

```
Here's the AppSettings class:
```
public class AppSettings
{
	public Info Info { get; set; }        
}

public class Info
{
	public string Name { get; set; }
	public string Version { get; set; }
}

```
Here's the appsettings.json:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  },
  "AppSettings": {
    "Info": {
      "Name": "Test Service",
      "Version": "v1"
    }
  }
}
```

Full Stack Trace:
```
: System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.<>c.<CreateHostBuilder>b__5_1(KestrelServerOptions options)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1 options, IConnectionListenerFactory transportFactory, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c957b4-4da9-2cda-b08e-ce78e5333768
* Version Independent ID: 2bf00fa5-70c1-b1a0-45c2-5a201f597066
* Content: [Self-hosted gRPC applications - gRPC for WCF developers](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/self-hosted#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/self-hosted.md](https://github.com/dotnet/docs/blob/master/docs/architecture/grpc-for-wcf-developers/self-hosted.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by KeishaW** [comment]
**Update:** The issue could lie with my use of Single File publish.
`dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true`

As a reminder, clicking the exe from the single file publish works fine but not using it as a Windows Service.

**Workaround:**
I had to specify the full path for the appsettings.json in `CreateHostBuilder` in order for the binding to work.

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
          Host.CreateDefaultBuilder(args)
              .UseWindowsService()
              .ConfigureWebHostDefaults(webBuilder =>
              {
                  webBuilder.UseStartup<Startup>();
              })
             .ConfigureAppConfiguration((hostingContext, config) =>
             {
                 var env = hostingContext.HostingEnvironment;

                 string basePath = string.Empty;

#if !DEBUG
                 basePath = $"{Path.GetDirectoryName(System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName)}\\"; 
#endif
                 config.AddJsonFile($"{basePath}appsettings.json", optional: true, reloadOnChange: true)
                        .AddJsonFile($"{basePath}appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
             });
```
