### ISSUE TITLE
Yeoman Generator Aspnet Do Not Run Into Docker Container

### ISSUE THREAD

**Issue by mestihudson** [dotnet/docs#2505]
Hi,

I am trying to generate `yo aspnet` into docker container but this message always is show:

`
+ gulp@3.9.1
+ yo@2.0.0
+ bower@1.8.0
+ grunt-cli@1.2.0
+ generator-aspnet@0.3.3
added 1008 packages in 66.338s
npm info ok 
root@ffe35c5dda6b:/# yo -v
/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:53
                                throw err;
                                ^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Configstore.get (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Configstore.get (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:81:13)
    at Insight.get (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:48:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:194:47)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
`

**Comment by mairaw** [comment]
@kendrahavens can you help here? do you know anything about this? Thanks!

**Comment by kendrahavens** [comment]
@mestihudson Usually permission denied errors can be solved by running in a privileged command prompt or terminal. This would be sudo on linux or administrator mode on windows. If you are actually ssh-ing into the container, try running the docker container with the --privileged flag.

Also, please note the yo docker generator is very out of date. (Though sounds like you are using the yo aspnet generator) We are looking into fixing that experience soon!

**Comment by JRAlexander** [comment]
This article is moving to the ASP.NET repo as part of the .NET Core 2.0 update. This issue will be resolved then.
