### ISSUE TITLE
The example code in DI depends on whether docker is used or not.

### ISSUE THREAD

**Issue by jinhoyim** [dotnet/docs#25327]
The code below works in Linux Docker environment, but does not work without Docker.

```C#
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace DependencyInjection.Example
{
    class Program
    {
        static Task Main(string[] args) =>
            CreateHostBuilder(args).Build().RunAsync();

        static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((_, services) =>
                    services.AddHostedService<Worker>()
                            .AddScoped<IMessageWriter, MessageWriter>());
    }
}
```

The exception that occurs when docker is not used is as follows.
```Shell
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: DependencyInjection.Example.Worker': Cannot consume scoped service 'DependencyInjection.Example.IMessageWriter' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: DependencyInjection.Example.Worker': Cannot consume scoped service 'DependencyInjection.Example.IMessageWriter' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.
 ---> System.InvalidOperationException: Cannot consume scoped service 'DependencyInjection.Example.IMessageWriter' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitRootCache(ServiceCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnCreate(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at DependencyInjection.Example.Program.Main(String[] args) in C:\Projects\Study\docs-ms\DependencyInjection.Example\DependencyInjection.Example\Program.cs:line 14
```

I read it ["If a scoped service is created in the root container, the service's lifetime is effectively promoted to singleton because it's only disposed by the root container when the app shuts down."](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scope-validation).
Are there any prerequisites for a service to be promoted to a singleton?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd55089-b683-2202-6641-c7b61a132f14
* Version Independent ID: cc5f00d0-fb50-1229-8fa2-e66b1f45b284
* Content: [Dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#feedback)
* Content Source: [docs/core/extensions/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/dependency-injection.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by davidfowl** [comment]
Right, it has nothing to do with docker but it fails because in development we do more verification on the container. The problem is your hosted service is a singleton and you're trying to consume a scoped service from it (essentially upgrading the scoped service to a singleton).

**Comment by jinhoyim** [comment]
@davidfowl It works when the environment variable 'DOTNET_ENVIRONMENT' is not 'Development'.
Thank you.

**Comment by davidfowl** [comment]
"Works", it throws because the DI container is trying to warn you that injecting a scoped into a singleton might be dangerous.

**Comment by stijnherreman** [comment]
@davidfowl the very first example does just that, injecting a scoped service into a singleton. Presumably that part of the documentation was written back when `AddHostedService` still registered as transient?
