### ISSUE TITLE
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 

### ISSUE THREAD

**Issue by iRejish** [dotnet/docs#26546]
Using the suggested name for the project with a `.` is causing the following error when trying to run the project later:

`dotnet new console -o App -n NetCore.Docker`
`dotnet run`

```
System.ComponentModel.Win32Exception (5): An error occurred trying to start process '<root>\App\bin\Debug\net6.0\NetCore.Docker.exe' with working directory '<root>\App'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa
* Version Independent ID: 58d57b81-4ca6-6536-8788-f212402b41a7
* Content: [Containerize an app with Docker tutorial - .NET](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows)
* Content Source: [docs/core/docker/build-container.md](https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @iRejish, you're getting an access denied error. I do not believe it has anything to do with the `.` in the file name. In fact, that error itself shows that the file name correctly.

```
System.ComponentModel.Win32Exception (5): An error occurred trying to start process '<root>\App\bin\Debug\net6.0\NetCore.Docker.exe' with working directory '<root>\App'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```
