### ISSUE TITLE
I'm trying to read mongdb， there is error

### ISSUE THREAD

**Issue by robyle** [dotnet/docs#28367]
**Issue description**

**Target framework**

- [ x ] .NET Core 5.0

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET SDK (反映任何 global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2
```

</details>
<p>
<b>Here is my get errors:</b>

JvmException: java.lang.NoClassDefFoundError: org/bson/conversions/Bson
	at com.mongodb.spark.sql.DefaultSource.constructRelation(DefaultSource.scala:89)
	at com.mongodb.spark.sql.DefaultSource.createRelation(DefaultSource.scala:50)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:165)
	at org.apache.spark.api.dotnet.DotnetBackendHandler$$anonfun$handleBackendRequest$1.apply$mcV$sp(DotnetBackendHandler.scala:105)
	at org.apache.spark.api.dotnet.ThreadPool$$anon$1.run(ThreadPool.scala:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.bson.conversions.Bson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 18 more
![image](https://user-images.githubusercontent.com/11662528/155322005-3166ee61-ec53-4956-b372-ef2c715af33c.png)

</p>

**Comment by BillWagner** [comment]
hi :wave: @robyle 

I think you'll get a quicker response on the [Q & A](https://docs.microsoft.com/answers/products/dotnet) site section for .NET. Right now, it's unclear where to update any of the relevant docs to address this.

**Comment by robyle** [comment]
> hi 👋 @robyle
> 
> I think you'll get a quicker response on the [Q & A](https://docs.microsoft.com/answers/products/dotnet) site section for .NET. Right now, it's unclear where to update any of the relevant docs to address this. Please let us know if you've found an answer, or can point to the docs that led you astray.

Hi，I just follow the offical website: https://learn.microsoft.com/zh-cn/dotnet/spark/how-to-guides/connect-to-mongo-db

I run it，it will get the problem like my uploaded picture.
