### ISSUE TITLE
.NET 6 IdentityUI Bootstrap License File Location Change

### ISSUE THREAD

**Issue by fceci90** [dotnet/docs#32884]
It seems as though the location for the license file is changed as well for IndentityUI in .NET 6. I was unable to publish after upgrading to .NET 6.

Publish error:
> Web deployment task failed. (Unable to perform the operation ("Create File") for the specified directory ("C:\Inetpub\wwwroot\MyProjectName\wwwroot\Indentity\lib\boostrap\LICENSE"). This can occur if the server administrator has not authorized this operation for the user credentials you are using. Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.

In my previous file structure (based on ASP.NET Core 3.1 publishing) within the wwwroot\Identity\lib\bootstrap folder there were two folders; dist, containing the library itself, and a LICENSE folder containing a license filed named LICENSE. 

Removing the entire LICENSE folder allowed me to publish successfully. After publishing, the LICENSE file is now directly in the root of the boostrap folder, and no longer nested within another folder called LICENSE. 

For those people migrating from .NET Core 3.1 or .NET 5 to .NET 6, in addition to adding `<IdentityUIFrameworkVersion>Bootstrap4</IdentityUIFrameworkVersion>`
to their csproj file to keep the Bootstrap version at 4, I would also recommend adding the removable of the LICENSE folder prior to publishing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7a18c8-acae-f101-fcbd-f3b79f4e7c9f
* Version Independent ID: 266e32ee-567e-f8dd-7da8-e82c277aab1c
* Content: [Breaking change: Default version of Bootstrap used with Identity now 5 - .NET](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/identity-bootstrap4-to-5)
* Content Source: [docs/core/compatibility/aspnet-core/6.0/identity-bootstrap4-to-5.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/6.0/identity-bootstrap4-to-5.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @serpent5
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@HaoK @Rick-Anderson Should further information be added to this breaking change article?

**Comment by Rick-Anderson** [comment]
> @HaoK @Rick-Anderson Should further information be added to this breaking change article?

@Haok moved to a different team.

The link states:

Resolution: Grant the appropriate account Full Control on the site's root folder. Alternatively:

**Comment by Rick-Anderson** [comment]
We've had so many customers update from 3.1 and 5.0 to 6.0 and I've never heard of that problem.  At most I would add  ``## Additional information``
See [this GithHub issue](https://github.com/dotnet/docs/issues/32884) if you encounter the following publishing error Web deployment task failed. (Unable to perform the operation ("Create File") for the specified directory ("C:\Inetpub\wwwroot\MyProjectName\wwwroot\Indentity\lib\boostrap\LICENSE").

**Comment by akhilesh84** [comment]
I get the same error when trying to deploy an app upgraded from .NET6.0 to .NET8.0.

Error Code: ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER
More Information: Unable to perform the operation ("Create File")  for the specified directory ("C:\home\site\wwwroot\wwwroot\Identity\lib\bootstrap\LICENSE"). This can occur if the server administrator has not authorized this operation for the user credentials you are using.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.  Learn more at: https://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.
Error: The error code was 0x80070005. ---> System.Exception: Access to the path 'C:\home\site\wwwroot\wwwroot\Identity\lib\bootstrap\LICENSE' is denied.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)
   --- End of inner exception stack trace --- 
Error: Access to the path 'C:\home\site\wwwroot\wwwroot\Identity\lib\bootstrap\LICENSE' is denied.
   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable`1 fileLength)
   at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)
Error count: 1.
