### ISSUE TITLE
ILGenerator.BeginFinallyBlock example is invalid

### ISSUE THREAD

**Issue by svick** [dotnet/docs#3351]
As discovered by @luboid in https://github.com/dotnet/coreclr/issues/14379#issuecomment-334959413, [the example code for `ILGenerator.BeginFinallyBlock`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.beginfinallyblock?view=netcore-2.0#Examples) contains branch out of try block and is thus invalid. When I run it on .Net Framework 4.7 or .Net Core 2.0 (after changing `myAppDomain.DefineDynamicAssembly` to `AssemblyBuilder.DefineDynamicAssembly` and removing the permissions attribute to make it compile on .Net Core 2.0), I get the following exception:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Adder.DoAdd(Int32 , Int32 )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   at ILGenerator_BeginFinallyBlock.Main() in C:\code\tmp\coreapp\Program.cs:line 109
```

I think the example should be changed, so that it produces valid IL.

**Comment by mairaw** [comment]
Thanks @svick for reporting this issue. We're adding this item to our backlog.

**Comment by garg000dhruv** [comment]
@mairaw I can take this up if you'd like.

**Comment by rpetrusha** [comment]
If you would like to work on this, @garg000dhruv, that would be really great. I'll assign it to you.
Incidentally, although the ECMA spec explicitly disallows a return from a try region, it was not enforced until the new 64-bit JIT compiler introduced in the .NET Framework 4.6. See "IL ret not allowed in a try region" in the list of [app compat issues between 4.5 and 4.6](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5.2-4.6).

**Comment by garg000dhruv** [comment]
@rpetrusha That's what I was wondering because when I run the example on my machine, it runs just fine. I'll try with the updated specs and see what happens. But yeah I'd love to take this one up.

**Comment by garg000dhruv** [comment]
@mairaw Let me know if I can start work on this. I only asl because I didn't see the ```up-for-grabs``` label removed or the issue moved to ```to-do```.

**Comment by rpetrusha** [comment]
@garg000dhruv, you can start work on this issue. I've removed the up-for-grabs label. Since the issue is not part of a project, though, it can't be moved to either to-do or in-progress. We'll set the milestone when your PR arrives.
