### ISSUE TITLE
TextExpressionCompiler(settings).Compile()  runtime compile issue

### ISSUE THREAD

**Issue by minhlieubk** [dotnet/docs#36271]
Hi,

Please help
We are facing with a runtime issue, after few hours running, we got this compile issue

WebHost failed to process a request.
 Sender Information: System.ServiceModel.ServiceHostingEnvironment+HostingManager/12596525
 Exception: System.ServiceModel.ServiceActivationException: The service '/xxxxxxxxx/yyyyyyyyyyyy.svc' cannot be activated due to an exception during compilation.  The exception message is: Could not load file or assembly 'file:///C:\Windows\TEMP\p1r5rduo\p1r5rduo.dll' or one of its dependencies. The system cannot find the file specified.. ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Windows\TEMP\p1r5rduo\p1r5rduo.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity)
   at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
   at System.Activities.XamlIntegration.TextExpressionCompiler.CompileInMemory()
   at xxxxxxxxxxxw.xxxWorkflowServiceHostFactory.CompileExpressions(Activity activity) in D:\agent\_work\2453\s\xxxxxxxxxx\xxxWorkflowServiceHostFactory.cs:line 46
   at xxxxxxxxxxxx.xxxWorkflowServiceHostFactory.CreateWorkflowServiceHost(WorkflowService service, Uri[] baseAddresses) in D:\agent\_work\2453\s\xxxxxxxxxx\xxxWorkflowServiceHostFactory.cs:line 15
   at System.ServiceModel.Activities.Activation.WorkflowServiceHostFactory.CreateServiceHost(String constructorString, Uri[] baseAddresses)
   at System.ServiceModel.ServiceHostingEnvironment.HostingManager.CreateService(String normalizedVirtualPath, EventTraceActivity eventTraceActivity)
   at System.ServiceModel.ServiceHostingEnvironment.HostingManager.ActivateService(ServiceActivationInfo serviceActivationInfo, EventTraceActivity eventTraceActivity)
   at System.ServiceModel.ServiceHostingEnvironment.HostingManager.EnsureServiceAvailable(String normalizedVirtualPath, EventTraceActivity eventTraceActivity)
   --- End of inner exception stack trace ---
   at System.ServiceModel.ServiceHostingEnvironment.HostingManager.EnsureServiceAvailable(String normalizedVirtualPath, EventTraceActivity eventTraceActivity)
   at System.ServiceModel.ServiceHostingEnvironment.EnsureServiceAvailableFast(String relativeVirtualPath, EventTraceActivity eventTraceActivity)
 Process Name: w3wp
 Process ID: 14792

We use Using C# expressions in code workflows to host the workflow
 // Create a TextExpressionCompilerSettings.
    TextExpressionCompilerSettings settings = new TextExpressionCompilerSettings
    {
        Activity = activity,
        Language = "C#",
        ActivityName = activityType,
        ActivityNamespace = activityNamespace,
        RootNamespace = null,
        GenerateAsPartialClass = false,
        AlwaysGenerateSource = true,
        ForImplementation = false
    };

    // Compile the C# expression.
    TextExpressionCompilerResults results =
        new TextExpressionCompiler(settings).Compile();

Many thanks,
Minh

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30cf5e1f-8677-970b-6de9-f20c652f7f1d
* Version Independent ID: f87530b3-00e2-8b9e-0d54-93c7ce530778
* Content: [C# Expressions - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/csharp-expressions?redirectedfrom=MSDN#WFServices)
* Content Source: [docs/framework/windows-workflow-foundation/csharp-expressions.md](https://github.com/dotnet/docs/blob/main/docs/framework/windows-workflow-foundation/csharp-expressions.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wf**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by mail2rameshthota** [comment]
Any update on this issue, even we are facing similar issue.

**Comment by adegeo** [comment]
We can't really support customer code questions and issues via the docs. You're better off asking questions on a support forum like StackOverflow and if you find an improvement to make in the documentation, bring it up. Sorry.
