### ISSUE TITLE
Code does not work in EKS linux host

### ISSUE THREAD

**Issue by Tavisca-sagar-patil3** [dotnet/docs#38519]
### Type of issue

Code doesn't work

### Description

[Background: This code runs well in visual studio 2022 professional (both windows and macOS) and as well as in if .Net 6 web api is deployed in IIS on windows server. But it does not work for kestrel server and deployed in Elastic Kubernetes service(EKS)
Limitation: 1. The path dependency while loading the training model. _mlContext.Model.Load(string trainedmodelpath, out modelschema);
2. The path from where training images are fed to generate the trained model is somehow have dependency on same path when images used for prediction. So, when our web api is deployed in EKS behind Kestrel server then it really does not work as it cannot find either System.AppDomain.CurrentDomain.BaseDirectory or System.Environment.CurrentDirectory. 
Code: predictor.Predict(imageData);
Severity: This is now blocker for us for EKS deployment]

### Page URL

https://learn.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/machine-learning/tutorials/image-classification.md

### Document Version Independent Id

c8a996eb-82ed-a4bd-94d8-ef0b32158c67

### Article author

@luisquintanilla

### Metadata

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c 
* Product: **dotnet-ml**

**Comment by Tavisca-sagar-patil3** [comment]
Exception stack trace:   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstanceCore(Object[] ctorArgs)
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstance(IHostEnvironment env, Object args, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes](IHostEnvironment env, Type signatureType, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes,TSig](IHostEnvironment env, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModelCore[TRes,TSig](IHostEnvironment env, TRes& result, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModelOrNull[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
