### ISSUE TITLE
In the plugin mode of dotnet8, the native related dll files in runtimes cannot be loaded correctly.

### ISSUE THREAD

**Issue by FisherMS** [dotnet/docs#41942]
### Type of issue

Code doesn't work

### Description

In the plugin mode of dotnet8, the native related dll files in runtimes cannot be loaded correctly.

When using Microsoft.EntityFrameworkCore.Sqlite in a plug-in, if it is not introduced in the main project. an exception will be throwed.

```log
Unable to load DLL 'e_sqlite3' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

The sample code Url : https://github.com/DevStudy/PluginSample/tree/dev/v1

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/core/tutorials/creating-app-with-plugin-support

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/creating-app-with-plugin-support.md

### Document Version Independent Id

f25a6e1a-cb10-867b-0522-a377bf9d016b

### Article author

@jkoritzinsky

### Metadata

* ID: 06023407-704f-0ace-e89a-eedd9f95a007 
* Service: **dotnet-fundamentals**

**Comment by FisherMS** [comment]
Impletment the class AssemblyLoadContext 's method 

 protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
{
}
and it's solved
