### ISSUE TITLE
Source column "Label" not found

### ISSUE THREAD

**Issue by mnbuch** [dotnet/docs#5628]
I am getting this error. Following is the stack trace:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.Run()
   at Microsoft.ML.Runtime.EntryPoints.EntryPointGraph.RunNode(EntryPointNode node)
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAllNonMacros()
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAll()
   at Microsoft.ML.LearningPipeline.Train[TInput,TOutput]()
   at TaxiFarePrediction.Program.<Train>d__5.MoveNext() in E:\startsomething\ml\TaxiFarePrediction\TaxiFarePrediction\Program.cs:line 55

Inner Exception 1:
ArgumentOutOfRangeException: Source column 'Label' not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York Taxi Fares (Regression)](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Service: **unspecified**
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by mnbuch** [comment]
Fixed it. My Bad.

For others here is what I did wrong: Make sure there are 2 brackets in the ColumnCopier Ctor

pipeline.Add(new ColumnCopier(("fare_amount", "Label")));

**Comment by JRAlexander** [comment]
Nicely done, @mnbuch!
