### ISSUE TITLE
There is no get_Evidence in the stacktrace!

### ISSUE THREAD

**Issue by poizan42** [dotnet/docs#6756]
At least on .NET 4.7.2 (release 461814)

Here is an example of a stacktrace from a System.Runtime.Serialization.SerializationException caused by the mentioned issue.
```
   at System.AppDomain.GetHostEvidence(Type type)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Data.SqlClient.SqlConnection..cctor()
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9d373c8-0d4a-68cb-69f2-67faa96c44b2
* Version Independent ID: 15bbda61-8313-1f5f-3a89-4634eb148021
* Content: [Mitigation: Deserialization of Objects Across App Domains](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-deserialization-of-objects-across-app-domains)
* Content Source: [docs/framework/migration-guide/mitigation-deserialization-of-objects-across-app-domains.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/mitigation-deserialization-of-objects-across-app-domains.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

---
[Associated WorkItem - 558440](https://dev.azure.com/msft-skilling/Content/_workitems/edit/558440)

**Comment by mairaw** [comment]
@rpetrusha @chlowell can you help with this issue? This is in the migration guide path but there's no TOC for this.

**Comment by poizan42** [comment]
This issue is still present in the documentation as far as I can tell. [AppDomainEvidenceFactory.GenerateEvidence calls AppDomain.GetHostEvidence](https://referencesource.microsoft.com/#mscorlib/system/security/policy/appdomainevidencefactory.cs,89) in the not-default-appdomain case.

**Comment by BillWagner** [comment]
This fix is to include instructions for cross-app domain calls. Note that those are framework only, and provide additional mitigation steps for that use case.
