### ISSUE TITLE
Error, 403 (Forbidden)

### ISSUE THREAD

**Issue by JohnMarsing** [dotnet/docs#8802]
I'm getting an error when I do this...

var repositories = serializer.ReadObject(await streamTask) as List&lt;repo&gt;;  

Here's the error message...
Unhandled Exception: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).) ---&gt; System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   at WebAPIClient.Program.ProcessRepositories() in D:\Sample Projects\console-webapiclient\Program.cs:line 26
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WebAPIClient.Program.Main(String[] args) in D:\Sample Projects\console-webapiclient\Program.cs:line 19

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient#conclusion)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JohnMarsing** [comment]
I got this to work, how do I delete this?

**Comment by shreyas-github** [comment]
how did you get it to work?

**Comment by shreyas-github** [comment]
safsad
