### ISSUE TITLE
removing the endpoint section from the App.config errors out

### ISSUE THREAD

**Issue by andreireiand** [dotnet/docs#9773]
with error:

System.InvalidOperationException: Service 'GettingStartedLib.CalculatorService' has zero application (non-infrastructure) endpoints. This might be because no configuration file was found for your application, or because no service element matching the service name could be found in the configuration file, or because no endpoints were defined in the service element.
   at System.ServiceModel.Description.DispatcherBuilder.EnsureThereAreApplicationEndpoints(ServiceDescription description)
   at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
   at System.ServiceModel.ServiceHostBase.InitializeRuntime()
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at Microsoft.Tools.SvcHost.ServiceHostHelper.OpenService(ServiceInfo info)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c8cbb16-05b1-a5f2-9031-1d7beb52efea
* Version Independent ID: 98092a9f-c19a-cca9-75d6-75b9c3d4cc0b
* Content: [How to: Host and Run a Basic Windows Communication Foundation Service](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-host-and-run-a-basic-wcf-service)
* Content Source: [docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
You can't remove the endpoint information as it's configuring your client. You should be able to search a forum like stackoverflow for how to use a WCF service without the app.config file.

Thanks.
